Add Karma package
sighupio/fury-kubernetes-monitoring pull request #143
Opened 2023-03-13 14:09 UTC by sbruzzese902

As per the PR title, I'm adding Karma as part of the monitoring module.

There aren't official Karma manifests for Kubernetes yet, so this is a simple standard setup.

Any comment or suggestion is more than welcomed 😄

2023-03-13 15:35 UTC, ralgozino requested changes
some minor corrections

2023-03-13 15:35 UTC, ralgozino commented on katalog/karma/README.md
> +- Polling interval: `1m`
linter will complain if you don't leave an empty line before a list
```suggestion
configuration:

- Alertmanager URI: `http://alertmanager-main.monitoring.svc.cluster.local:9093`
- Polling interval: `1m`
```

2023-03-13 15:35 UTC, ralgozino commented on katalog/karma/README.md
> +All configuration options can be found [here](https://github.com/prymitive/karma/blob/main/docs/CONFIGURATION.md)
I suggest linking to the docs for the version we are using:

```suggestion
All configuration options can be found [here](https://github.com/prymitive/karma/blob/v0.113/docs/CONFIGURATION.md)
```

pointing to `main` has the downside that the file contents could change or even disappear :)

2023-03-13 15:35 UTC, ralgozino commented on katalog/karma/README.md
> +You can deploy karma by running the following command:
linting
```suggestion
## Deployment

You can deploy karma by running the following command:
```

maybe we can say something about how to create the configuration patch here?

2023-03-13 15:35 UTC, ralgozino commented on katalog/karma/deployment.yaml
> +        name: config
nitpick: missing new line at the end of the file

2023-03-13 16:36 UTC, ralgozino requested changes

2023-03-13 16:57 UTC, ralgozino requested changes
Sorry Simo for the several requests for change, I just realised that the main readme should be updated to add Karma to the packages table.

The rest lgtm

2023-03-13 16:59 UTC, sbruzzese902 commented
No problem! That's the reason for reviews 😄 I'm fixing it!

2023-03-14 15:57 UTC, ralgozino approved these changes
LGTM 💪

2023-03-14 16:06 UTC, nutellinoit approved these changes
LGTM 🚀

2023-03-15 09:59 UTC, merged