Docs/prepare release v2.1.0
sighupio/fury-kubernetes-monitoring pull request #147
Opened 2023-03-22 15:53 UTC by nutellinoit

2023-03-22 16:02 UTC, ralgozino requested changes
minor tweaks.

this PR is also doing a merge of `main` into the thanos PR, just double-checking that this is intended.

2023-03-22 16:02 UTC, ralgozino commented on katalog/configs/bases/coredns/dashboards/coredns.json
> +}
nitpick: missing new line at the end of file

2023-03-23 08:14 UTC, nutellinoit commented on docs/releases/v2.1.0.md
> +```
Yep, I think that for now we can also skip this guide and add it later

2023-03-23 08:21 UTC, ralgozino approved these changes
lgtm

2023-03-23 11:52 UTC, Deepzima commented
LGTM

2023-03-23 11:53 UTC, Deepzima approved these changes

2023-03-23 11:54 UTC, merged